layout: "main"
logger: "file"
appname: "jitterbug"

builds_per_feed: 5
template: "xslate"
engines:
  xslate:
    path: /
    type: text
    cache: 0

jitterbug:
  reports:
    dir: /tmp/jitterbug
  build:
    dir: /tmp/build
  build_process:
    builder: ./scripts/capsule.sh
    on_failure: ./scripts/build-failed.sh
  options:
    perlbrew: 1

plugins:
  DBIC:
    schema:
      skip_automake: 1
      pckg: "jitterbug::Schema"
      connect_info:
        - dbi:SQLite:dbname=jitterbug.db


