layout: "main"
logger: "file"
appname: "jitterbug"

redis: "127.0.0.1:6379"
template: "xslate"
engines:
  xslate:
    path: /
    type: text
    cache: 0

jitterbug:
  namespace: jitterbug
  reports:
    dir: /tmp/jitterbug
  build:
    dir: /tmp/build
  build_process:
    builder: ./scripts/capsule.sh
    on_failure: ./scripts/on_failure.sh
